# -*- coding: utf-8 -*-
"""tic-tac-toe-game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpVht_E-Em5KZiYkG-BXduX0jcvB8baz
"""

import random

# ============================================================
#                         CONSTANTS
# ============================================================

WINNING_COMBINATIONS = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9],
    [1, 5, 9],
    [3, 5, 7]
]

SEPARATOR = "=" * 55
LINE = "-" * 55


# ============================================================
#                      DISPLAY FUNCTIONS
# ============================================================

def show_welcome():
    """Display the welcome message."""
    print("\n" + SEPARATOR)
    print("                 TIC TAC TOE")
    print(SEPARATOR)
    print("\n        Welcome to Tic Tac Toe!")
    print("        Have fun and good luck! 🎮")
    print(SEPARATOR)


def show_section(title):
    """Display a section title."""
    print("\n" + LINE)
    print(f"                  {title}")
    print(LINE)


def show_board(board):
    """Display the Tic Tac Toe board."""
    print()
    print(f"              {board[0]} | {board[1]} | {board[2]}")
    print("             ---|---|---")
    print(f"              {board[3]} | {board[4]} | {board[5]}")
    print("             ---|---|---")
    print(f"              {board[6]} | {board[7]} | {board[8]}")
    print()


def show_scoreboard(scoreboard):
    """Display the current scoreboard."""
    show_section("SCOREBOARD")

    for player, score in scoreboard.items():
        print(f"              {player}: {score}")

    print(LINE)


def show_game_information(symbols):
    """Display the players and their symbols."""
    show_section("GAME INFORMATION")

    for symbol, player in symbols.items():
        print(f"              {player}: {symbol}")

    print()


# ============================================================
#                       INPUT FUNCTIONS
# ============================================================

def choose_game_mode():
    """Ask the user to choose the game mode."""

    while True:
        show_section("GAME MODE")

        print("              1. Player vs Player")
        print("              2. Player vs Computer")
        print("              3. Quit")

        try:
            choice = int(input("\n              Select your mode: "))
        except ValueError:
            print("\n              Invalid input! Please enter 1, 2, or 3.")
            continue

        if choice in (1, 2, 3):
            return choice

        print("\n              Wrong choice! Please try again.")


def get_player_names(mode):
    """Get player names according to the selected mode."""

    show_section("PLAYER INFORMATION")

    if mode == 1:
        while True:
            player_one = input(
                "              Enter Player 1 name: "
            ).strip()

            player_two = input(
                "              Enter Player 2 name: "
            ).strip()

            if not player_one or not player_two:
                print("\n              Names cannot be empty.")
                continue

            if player_one.lower() == player_two.lower():
                print(
                    "\n              Players must have different names."
                )
                continue

            return player_one, player_two

    player_one = input(
        "              Enter your name: "
    ).strip()

    while not player_one:
        print("\n              Name cannot be empty.")
        player_one = input(
            "              Enter your name: "
        ).strip()

    return player_one, "Computer"


def choose_symbol(player_name):
    """Let the player choose X or O."""

    while True:
        show_section("SYMBOL SELECTION")

        print(f"              {player_name}, choose your symbol:")
        print()
        print("              1. X")
        print("              2. O")

        try:
            choice = int(input("\n              Select: "))
        except ValueError:
            print("\n              Invalid input! Please enter 1 or 2.")
            continue

        if choice == 1:
            return "X"

        if choice == 2:
            return "O"

        print("\n              Wrong choice! Please try again.")


def get_player_move(player_name, board):
    """Get a valid move from a human player."""

    while True:
        try:
            move = int(
                input(
                    f"              {player_name} ---> "
                    "Select a box (1-9): "
                )
            )
        except ValueError:
            print("\n              Invalid input! Enter a number from 1 to 9.")
            continue

        if move < 1 or move > 9:
            print(
                "\n              Wrong number! "
                "Choose a number from 1 to 9."
            )
            continue

        if board[move - 1] != " ":
            print("\n              Oops! This box is already selected.")
            continue

        return move


# ============================================================
#                        GAME LOGIC
# ============================================================

def check_victory(player_positions, current_symbol):
    """Check whether the current player has won."""

    for combination in WINNING_COMBINATIONS:
        if all(
            position in player_positions[current_symbol]
            for position in combination
        ):
            return True

    return False


def check_tie(player_positions):
    """Check whether the game is a draw."""

    total_moves = (
        len(player_positions["X"])
        + len(player_positions["O"])
    )

    return total_moves == 9


def get_available_positions(board):
    """Return all available board positions."""

    return [
        position
        for position in range(1, 10)
        if board[position - 1] == " "
    ]


def get_computer_move(board):
    """Choose a random available position for the computer."""

    available_positions = get_available_positions(board)

    return random.choice(available_positions)


# ============================================================
#                         SINGLE GAME
# ============================================================

def play_game(current_player, symbols, player_mode):
    """Play one complete Tic Tac Toe game."""

    board = [" " for _ in range(9)]

    player_positions = {
        "X": [],
        "O": []
    }

    while True:

        show_board(board)

        current_symbol = (
            "X" if symbols["X"] == current_player else "O"
        )

        # ----------------------------------------------------
        #                    PLAYER MOVE
        # ----------------------------------------------------

        if current_player == "Computer":

            move = get_computer_move(board)

            print(
                f"              Computer ---> "
                f"Selected box: {move}"
            )

        else:

            move = get_player_move(
                current_player,
                board
            )

        # ----------------------------------------------------
        #                 UPDATE GAME STATE
        # ----------------------------------------------------

        board[move - 1] = current_symbol
        player_positions[current_symbol].append(move)

        # ----------------------------------------------------
        #                  CHECK VICTORY
        # ----------------------------------------------------

        if check_victory(
            player_positions,
            current_symbol
        ):
            show_board(board)

            if current_player == "Computer":
                print("              🤖 Computer has won the game!")
            else:
                print(
                    f"              🏆 "
                    f"{current_player} has won the game!"
                )

            return current_player

        # ----------------------------------------------------
        #                    CHECK TIE
        # ----------------------------------------------------

        if check_tie(player_positions):
            show_board(board)

            print("              🤝 Game Tied!")

            return "D"

        # ----------------------------------------------------
        #                   SWITCH PLAYER
        # ----------------------------------------------------

        if player_mode == "computer":

            if current_player == "Computer":
                current_player = symbols["X"]
                if current_player == "Computer":
                    current_player = symbols["O"]
            else:
                current_player = "Computer"

        else:

            if current_player == symbols["X"]:
                current_player = symbols["O"]
            else:
                current_player = symbols["X"]


# ============================================================
#                     GAME CONFIGURATION
# ============================================================

def setup_game(mode, player_one, player_two):
    """Configure players and symbols for a new game."""

    player_symbol = choose_symbol(player_one)

    if mode == 1:

        if player_symbol == "X":
            symbols = {
                "X": player_one,
                "O": player_two
            }
        else:
            symbols = {
                "X": player_two,
                "O": player_one
            }

        player_mode = "player"

    else:

        if player_symbol == "X":
            symbols = {
                "X": player_one,
                "O": "Computer"
            }
        else:
            symbols = {
                "X": "Computer",
                "O": player_one
            }

        player_mode = "computer"

    return symbols, player_mode


# ============================================================
#                       SCOREBOARD
# ============================================================

def update_score(scoreboard, winner):
    """Update the winner's score."""

    if winner != "D":
        scoreboard[winner] += 1


# ============================================================
#                          MAIN
# ============================================================

def main():
    """Run the Tic Tac Toe game."""

    show_welcome()

    while True:

        # ----------------------------------------------------
        #                    CHOOSE MODE
        # ----------------------------------------------------

        mode = choose_game_mode()

        if mode == 3:
            print("\n              Thanks for playing!")
            print(SEPARATOR)
            break

        # ----------------------------------------------------
        #                   PLAYER NAMES
        # ----------------------------------------------------

        player_one, player_two = get_player_names(mode)

        # ----------------------------------------------------
        #                    SCOREBOARD
        # ----------------------------------------------------

        scoreboard = {
            player_one: 0,
            player_two: 0
        }

        # ----------------------------------------------------
        #                    GAME LOOP
        # ----------------------------------------------------

        while True:

            # ------------------------------------------------
            #                 SETUP GAME
            # ------------------------------------------------

            symbols, player_mode = setup_game(
                mode,
                player_one,
                player_two
            )

            show_game_information(symbols)

            # ------------------------------------------------
            #                  WHO STARTS?
            # ------------------------------------------------

            if symbols["X"] == "Computer":
                current_player = "Computer"
            else:
                current_player = symbols["X"]

            print(
                f"              {current_player} "
                "will make the first move!"
            )

            # ------------------------------------------------
            #                    PLAY GAME
            # ------------------------------------------------

            winner = play_game(
                current_player,
                symbols,
                player_mode
            )

            # ------------------------------------------------
            #                  UPDATE SCORE
            # ------------------------------------------------

            update_score(scoreboard, winner)

            # ------------------------------------------------
            #                 DISPLAY RESULT
            # ------------------------------------------------

            show_section("GAME RESULT")

            if winner == "D":
                print("              The game ended in a draw.")
            else:
                print(f"              Winner: {winner}")

            show_scoreboard(scoreboard)

            # ------------------------------------------------
            #                  PLAY AGAIN?
            # ------------------------------------------------

            while True:

                print("              1. Play another game")
                print("              2. Change game mode")
                print("              3. Quit")

                try:
                    next_choice = int(
                        input("\n              Select: ")
                    )
                except ValueError:
                    print(
                        "\n              Invalid input! "
                        "Please enter 1, 2, or 3."
                    )
                    continue

                if next_choice == 1:
                    break

                if next_choice == 2:
                    break

                if next_choice == 3:
                    show_section("FINAL RESULT")
                    show_scoreboard(scoreboard)

                    print("\n              Thanks for playing!")
                    print(SEPARATOR)
                    return

                print(
                    "\n              Wrong choice! "
                    "Please try again."
                )

            # ------------------------------------------------
            #          CONTINUE OR CHANGE GAME MODE
            # ------------------------------------------------

            if next_choice == 2:
                break


# ============================================================
#                      PROGRAM START
# ============================================================

if __name__ == "__main__":
    main()